# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [ ]:
import numpy as np

2. Create a null vector of size 10 

In [ ]:
x = np.empty(10)

3. Create a vector with values ranging from 10 to 49

In [ ]:
x = np.arange(10,50)

4. Find the shape of previous array in question 3

In [ ]:
x.shape

(40,)

5. Print the type of the previous array in question 3

In [ ]:
print(x.dtype)

int64


6. Print the numpy version and the configuration


In [ ]:
print(np.__version__)
print(np.show_config())

1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [ ]:
print(x.ndim)

1


8. Create a boolean array with all the True values

In [ ]:
y = np.ones(10, dtype=bool)

9. Create a two dimensional array




In [ ]:
arr2d = np.arange(10).reshape(2,5)

10. Create a three dimensional array



In [ ]:
arr3d = np.arange(9).reshape(3,1,3)
print(arr3d)

[[[0 1 2]]

 [[3 4 5]]

 [[6 7 8]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [ ]:
arr = np.arange(10)
np.flip(arr)


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

12. Create a null vector of size 10 but the fifth value which is 1 

---



In [ ]:
nullVector = np.zeros(10)
nullVector[5] = 1

13. Create a 3x3 identity matrix

In [ ]:
iMatrix = np.identity(5)


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [ ]:
float_arr = arr.astype(np.float64)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [ ]:
arr1 = np.array([[1.,2.,3.],[4.,5.,6.]])
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
mul_arr = arr1*arr2

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [ ]:
arr1 = np.array([[1.,2.,3.],[4.,5.,6.]])
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])

comparison = arr1 ==arr2
print(comparison)

[[False False False]
 [False False False]]


17. Extract all odd numbers from arr with values(0-9)

In [ ]:
arr = np.arange(10)
condition = np.mod(arr, 2)!=0
extractedOdds = np.extract(condition,arr)
print(extractedOdds)

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [ ]:
arr = np.where(arr%2!=0,-1,arr)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [ ]:
arr = np.arange(10)
arr[5:9] = 12
print (arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [ ]:
array = np.ones(20).reshape(4,5)
array[1:-1,1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [ ]:
arr2d  = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d [1,1] =12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [ ]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d[0,0,:] = 64
print(arr3d)



[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [ ]:
array2d = np.arange(10).reshape(2,5)
slicedArray2d = array2d[0]
print(slicedArray2d)

[0 1 2 3 4]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [ ]:
anotherArray2d = np.arange(10).reshape(2, 5)
slicedAnotherArray2d = anotherArray2d[1,1]
print(slicedAnotherArray2d)

6


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [ ]:
a2d = np.arange(9).reshape(3, 3)
slicedA2d = a2d[:2,2:]



26. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
arr10x10 = np.random.randn(10,10)
minValue = np.min(arr10x10)
maxValue = np.max(arr10x10)
print(minValue)
print(maxValue)


-2.5691060072463294
2.0773436184119713


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [ ]:
a= np.array([1,2,3,2,3,4,3,4,5,6])
b= np.array([7,2,10,2,7,4,9,4,9,8])

c =np.intersect1d(a,b)
print(c)

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [ ]:
position = np.where(np.in1d(a, b))
print (position)

(array([1, 3, 5, 7]),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [ ]:
names = np.array(['Bob', 'Joe','Will', 'Bob','Will','Joe','Joe'])
data= np.random.randn(7,4)

data[names!='Will']



array([[-0.21987995,  0.71118843,  1.54436715,  0.36281057],
       [-0.20054714,  0.13493961,  0.1396932 , -0.87189326],
       [ 1.17907798, -0.3752533 , -0.88090659,  0.37185199],
       [-0.85621369, -3.43645347, -0.9619482 ,  0.59478247],
       [-1.41664636,  2.22956378,  0.96411091,  1.74398479]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [ ]:
names = np.array(['Bob', 'Joe','Will', 'Bob','Will','Joe','Joe'])
data= np.random.randn(7,4)
mask = (names!='Will')&(names!='Joe')

data[mask]



array([[ 1.27594098,  0.39548055, -0.32391946,  1.40568389],
       [ 0.55889405, -0.75644365, -0.71243931, -1.39844335]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [ ]:
newarr2d = np.arange(1,16).reshape(5,3)
print(newarr2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [ ]:
array1 = np.arange(1,17).reshape(2,2,4)
print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


33. Swap axes of the array you created in Question 32

In [ ]:
np.swapaxes(array1,0, 2)

array([[[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]],

       [[ 4, 12],
        [ 8, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [ ]:
array2 = np.random.randn(10)
sq = np.sqrt(array2)
s = np.where(sq<0.5,0,sq)
print(s)

[0.86453509        nan        nan        nan 1.77231773 0.82789527
        nan 0.55108959        nan        nan]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [ ]:
a1 = np.random.randn(12)
a2 = np.random.randn(12)

maxValues = np.maximum(a1, a2)
print (maxValues)

[ 2.26883607 -0.1183204   0.57089329  0.773427    0.85147157  0.81739643
  0.95684386  0.54801345  1.17502317  2.28279755 -0.73259878  0.50908289]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [ ]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

unames = np.unique(names)

np.sort(unames)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
result = np.setdiff1d(a, b)
print(result)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [ ]:
sampleArray = np.array([[34,43, 73],[82,22,12],[53,94,66]])

newColumn = np.array([10,10,10])

delA =np.delete(sampleArray,np.s_[1],axis=1)

ins = np.insert(delA,1,newColumn,1)
print (ins)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [ ]:
x = np.array([[1., 2.,3.],[4.,5.,6.]])
y = np.array([[6.,23.],[-1,7],[8,9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [ ]:
matrix = np.random.randn(20)
np.cumsum(matrix)

array([ 1.03171749,  0.7028681 ,  1.51051095, -0.78536093, -2.70475859,
       -1.62957162, -1.78893936, -1.81370352, -2.17346524, -0.46694471,
       -0.29508384, -0.4365186 , -0.98950693,  1.4891521 ,  2.08373979,
        1.36788057,  2.16591587,  2.94219448,  2.09060301,  1.80737151])