# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::


array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
arr1 = np.arange(10)
arr2d = arr1.reshape(2, 5)
print(arr2d)


[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [5]:
a = np.array([[0,1,2,3,4],[5,6,7,8,9]])
b = np.array([[1,1,1,1,1],[1,1,1,1,1]])
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [6]:
aa = np.array([[0,1,2,3,4],[5,6,7,8,9]])
bb = np.array([[1,1,1,1,1],[1,1,1,1,1]])

np.hstack((aa,bb))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a1 = np.array([[0,1,2,3,4],[5,6,7,8,9]])

a1.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [16]:
arr2 = np.arange(15).reshape(3, 1,5)
print (arr2)
arr2.ravel()

[[[ 0  1  2  3  4]]

 [[ 5  6  7  8  9]]

 [[10 11 12 13 14]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

array([[ 0, 1, 2],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])

In [22]:
arr3 = np.arange(15)
arr3.reshape(1,5,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [23]:
arr4 = np.arange(25).reshape(5, 5)
np.square(arr4)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

## Question:8

### Create 5x6 an array and find the mean?

In [24]:
arr5 = np.arange(30).reshape(5, 6)
np.mean(arr5)

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [25]:
np.std(arr5)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [26]:
np.median(arr5)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [27]:
np.transpose(arr5)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [31]:
arr6 = np.arange(16).reshape(4, 4)
print(arr6)
d = sum(np.diagonal(arr6))
print(d)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
30


## Question:13

### Find the determinant of the previous array in Q12?

In [32]:
np.linalg.det(arr6)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [35]:
arr7 =np.random.randn(3,3)
print(np.percentile(arr7,5))
print(np.percentile(arr7, 95))

-0.9114481980122461
1.7101438190778033


## Question:15

### How to find if a given array has any null values?

In [44]:
arr8 = np.empty(10)

print (arr8)
np.any(arr8)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


False